server {
    listen 80;
    root /var/www/html/public;
    index index.php index.html index.htm;
    server_name localhost;

    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_temp_file_write_size 64k;

    client_max_body_size 50M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # ✅ Forward headers so Laravel knows it's HTTPS
        # fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        # fastcgi_param HTTPS on;
    }

}