# Use the official PHP-FPM image
FROM php:8.2-fpm

COPY clear-laravel-caches.sh /usr/local/bin/clear-laravel-caches
RUN chmod +x /usr/local/bin/clear-laravel-caches

# Install required PHP extensions
RUN docker-php-ext-install bcmath

# Install system dependencies and PHP extensions needed by Laravel
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    zip \
    unzip \
    git \
 && docker-php-ext-configure gd --with-freetype --with-jpeg \
 && docker-php-ext-install gd pdo pdo_mysql

# Install Composer (copying it from the official Composer image)
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Fix permissions for Laravel (so Apache can read the files)
RUN chown -R www-data:www-data /var/www/html

# Expose PHP-FPM port (default 9000)
EXPOSE 9000

CMD ["php-fpm"]